### ISSUE TITLE
What diff between Do.addValues(1,2,3) and Do.add(Arrays.asList(1,2,3))

### ISSUE THREAD

**Issue by langzhaozhi** [aol/cyclops-react#175]
```
System.out.println( Do.add(ReactiveSeq.of("a","b","c"))
                .add(Arrays.asList(1,2,3))
                .yield(a->b->a + "#" + b)
                .toListX() );
```
works ok, but the following throws IllegalStateException( "stream has already been operated upon or closed") :: 

```
System.out.println( Do.add(ReactiveSeq.of("a","b","c"))
                .addValues(1,2,3)
                .yield(a->b->a + "#" + b)
                .toListX() );
```

What difference is about using the 2 api?
And works OK with  addStream(Supplier):

```
System.out.println( Do.add(ReactiveSeq.of("a","b","c"))
                .addStream(()->ReactiveSeq.of(1,2,3))
                .yield(a->b->a + "#" + b)
                .toListX() );
```

but exception with  a direct Stream:

```
 System.out.println( Do.add(ReactiveSeq.of("a","b","c"))
                .add(ReactiveSeq.of(1,2,3))
                .yield(a->b->a + "#" + b)
                .toListX() );
```

there may be need most unambiguous and explicit difference between of how to use them.

**Comment by johnmcclean-aol** [comment]
This is a bug that is fixed on a branch for release in RC3.

addValues creates a Stream, and reuses the Stream for each value in the monad at the level above, so we get Stream already closed exception.

I'll add more details on the RC3 changes later on this weekend.

**Comment by johnmcclean-aol** [comment]
Here are some more details on what is happening.  For comprehensions resolve to series of flatMap operations and finish with a map (yield operation). 

E.g. Add two Streams and then yielding with a simple sum resolves to something like this -

```java
   Stream.of(1,2,3).flatMap(a->Stream.of(4,5,6).map(b-> a+b));
```
The bug above is that we do something like this instead 

```java
   Stream<Integer> fourFiveSix = Stream.of(4,5,6);
   Stream.of(1,2,3).flatMap(a-> fourFiveSize.map(b-> a+b));
```

Which means we try to operate on fourFiveSix for every element in the Stream.of(1,2,3).

---

In the current implentation 'add' adds the supplied monad to the for comprehension without reference to the current values,

```java
System.out.println( Do.add(ReactiveSeq.of("a","b","c"))
                .addStream(()->ReactiveSeq.of(1,2,3))
                .yield(a->b->a + "#" + b)
                .toListX() );
```

Is equivalent to 

```java
ReactiveSeq.of("a","b","c").flatMap(a->ReactiveSeq.of(1,2,3).map(b-> a + "#" + b));
```

By contrast the with operators give specific access to the current context, so we can actually reference the current values of the first sequence when generating the second sequence.

In RC3, we will remove the 'add' based operators and only support 'with' type operators. As there is only one type of operator, we will drop the prefix and use the monad type as the method name (avoiding overloading because of the impact type inferencing has on compile times). Do also get's renamed to For.

So the ReactiveSeq example above would look something like this -

```java
System.out.println( For.stream(ReactiveSeq.of("a","b","c"))
                .stream(a->ReactiveSeq.of(1,2,3))
                .yield(a->b->a + "#" + b)
                .toListX() );
```

The add/with/Values methods have been removed, as it is probably less confusing to create the Stream or List directly yourself.

Also new in RC3 will be the ability to apply a for-comprehension via static methods that accept a given type (e.g. MonadicValue or reactive-streams Publisher). These will be written with a goal of support method references

That looks something like this 

```java
 For.publishers(Flux.just(1,2,3),this::generateStream,this::filter,this::add)
      .toListX();
```

Any feedback on the APIs appreciated!

**Comment by langzhaozhi** [comment]
Thank you for the detail explain, i have completely understand ! i like cyclops and learning how to use it  by typing some sample codes to run.

**Comment by langzhaozhi** [comment]
Hi, ask you a simple question. In  Idea IDE the code : 

`ReactiveSeq.of(1,2,3).filter(anyOf(not(in(2,3,4)),in(1,10,20)));`

same can be compiled and there are no errors report, but when i build code in gradle, it can not be compiled! The compile error message is it can not infer type. It is very strange.

**Comment by johnmcclean-aol** [comment]
Interesting, what version of Java 8 is this happening with? You can probably supply integer as an explicit generic type param to one of the Predicates, but that is not ideal either. I will investigate.

**Comment by johnmcclean-aol** [comment]
Changing the type signature of Predicates.in to 

       public static <T1> Predicate<T1> in(T1... values) 

Fixes this issue.

I will check the signatures of the other methods.

**Comment by langzhaozhi** [comment]
The JDK8 is 1.8.0_66-b18,  and i download the newest JDK8  1.8.0_77, the same problem. Both Javac and gradle build can not compile the code. But the strange thing is that, the Idea IDE tells no errors about the compile problem, the Idea IDE looks like that it can compile the code. I think this may be Java's bug, especitally for Java generic type-inferring when using SomeClass<? super T>.

**Comment by johnmcclean-aol** [comment]
Tracked in #217
